from django.urls import path

from core import views_membership

urlpatterns = [
    path(
        "membership/request/<int:pk>/rescind",
        views_membership.membership_request_rescind_api,
        name="api-membership-request-rescind",
    ),
    path(
        "membership/request/<int:pk>/approve",
        views_membership.membership_request_approve_api,
        name="api-membership-request-approve",
    ),
    path(
        "membership/request/<int:pk>/approve-on-hold",
        views_membership.membership_request_approve_on_hold_api,
        name="api-membership-request-approve-on-hold",
    ),
    path(
        "membership/request/<int:pk>/reject",
        views_membership.membership_request_reject_api,
        name="api-membership-request-reject",
    ),
    path(
        "membership/request/<int:pk>/rfi",
        views_membership.membership_request_rfi_api,
        name="api-membership-request-rfi",
    ),
    path(
        "membership/request/<int:pk>/ignore",
        views_membership.membership_request_ignore_api,
        name="api-membership-request-ignore",
    ),
    path(
        "membership/request/<int:pk>/reopen",
        views_membership.membership_request_reopen_api,
        name="api-membership-request-reopen",
    ),
    path(
        "membership/requests/bulk",
        views_membership.membership_requests_bulk_api,
        name="api-membership-requests-bulk",
    ),
    path(
        "membership/requests/pending",
        views_membership.membership_requests_pending_api,
        name="api-membership-requests-pending",
    ),
    path(
        "membership/requests/on-hold",
        views_membership.membership_requests_on_hold_api,
        name="api-membership-requests-on-hold",
    ),
    path(
        "membership/notes/<int:pk>/summary",
        views_membership.membership_request_notes_summary_api,
        name="api-membership-request-notes-summary",
    ),
    path(
        "membership/notes/<int:pk>",
        views_membership.membership_request_notes_api,
        name="api-membership-request-notes",
    ),
    path(
        "membership/notes/aggregate/summary",
        views_membership.membership_notes_aggregate_summary_api,
        name="api-membership-notes-aggregate-summary",
    ),
    path(
        "membership/notes/aggregate",
        views_membership.membership_notes_aggregate_api,
        name="api-membership-notes-aggregate",
    ),
    path(
        "membership/requests/<int:pk>/notes/add",
        views_membership.membership_request_notes_add_api,
        name="api-membership-request-notes-add",
    ),
    path(
        "membership/notes/aggregate/add",
        views_membership.membership_notes_aggregate_add_api,
        name="api-membership-notes-aggregate-add",
    ),
]
