from django.urls import path

from core import views_membership
from core.views_auth import (
    otp_sync_detail_api,
    password_expired_detail_api,
    password_reset_confirm_detail_api,
    password_reset_detail_api,
)
from core.views_elections.audit import (
    election_audit_log_api,
    election_audit_summary_api,
    election_public_audit,
    election_public_ballots,
)
from core.views_elections.ballot_verify import ballot_verify_api
from core.views_elections.detail import (
    election_detail_candidates_api,
    election_detail_eligible_voters_api,
    election_detail_ineligible_voters_api,
    election_detail_page_api,
    elections_api,
)
from core.views_elections.lifecycle import (
    election_conclude_api,
    election_extend_end_api,
    election_send_mail_credentials_api,
    election_tally_api,
)
from core.views_elections.reporting import elections_turnout_report_api, elections_turnout_report_detail_api
from core.views_elections.vote import election_vote_api, election_vote_submit
from core.views_groups import (
    group_action_api,
    group_detail_info_api,
    group_detail_leaders_api,
    group_detail_members_api,
    group_edit_api,
    groups_api,
)
from core.views_invitations_api import (
    account_invitations_accepted_api,
    account_invitations_accepted_detail_api,
    account_invitations_bulk_api,
    account_invitations_dismiss_api,
    account_invitations_pending_api,
    account_invitations_pending_detail_api,
    account_invitations_refresh_api,
    account_invitations_resend_api,
)
from core.views_mail_images import email_images_detail_api
from core.views_membership.admin import (
    stats_membership_summary_api,
)
from core.views_membership_admin import (
    membership_audit_log_detail_api,
    stats_membership_composition_charts_detail_api,
    stats_membership_retention_chart_detail_api,
    stats_membership_trends_charts_detail_api,
)
from core.views_organizations import organization_detail_page_api, organizations_api
from core.views_registration import (
    register_activate_detail_api,
    register_confirm_detail_api,
    register_detail_api,
)
from core.views_send_mail import send_mail_detail_api
from core.views_settings import settings_detail_api, settings_email_validate_detail_api
from core.views_templated_email import (
    email_template_create_detail_api,
    email_template_edit_detail_api,
    email_templates_detail_api,
)
from core.views_users import user_profile_detail_api, users_api

urlpatterns = [
    path(
        "users",
        users_api,
        name="api-users",
    ),
    path(
        "users/<str:username>/profile/detail",
        user_profile_detail_api,
        name="api-user-profile-detail",
    ),
    path(
        "organizations/<int:organization_id>/detail",
        organization_detail_page_api,
        name="api-organization-detail-page",
    ),
    path(
        "organizations",
        organizations_api,
        name="api-organizations",
    ),
    path(
        "groups",
        groups_api,
        name="api-groups",
    ),
    path(
        "groups/<str:name>/info",
        group_detail_info_api,
        name="api-group-detail-info",
    ),
    path(
        "groups/<str:name>/leaders",
        group_detail_leaders_api,
        name="api-group-detail-leaders",
    ),
    path(
        "groups/<str:name>/members",
        group_detail_members_api,
        name="api-group-detail-members",
    ),
    path(
        "groups/<str:name>/action",
        group_action_api,
        name="api-group-action",
    ),
    path(
        "groups/<str:name>/edit",
        group_edit_api,
        name="api-group-edit",
    ),
    path(
        "elections",
        elections_api,
        name="api-elections",
    ),
    path(
        "elections/<int:election_id>/detail",
        election_detail_page_api,
        name="api-election-detail-page",
    ),
    path(
        "elections/<int:election_id>/candidates",
        election_detail_candidates_api,
        name="api-election-detail-candidates",
    ),
    path(
        "elections/<int:election_id>/eligible-voters",
        election_detail_eligible_voters_api,
        name="api-election-detail-eligible-voters",
    ),
    path(
        "elections/<int:election_id>/ineligible-voters",
        election_detail_ineligible_voters_api,
        name="api-election-detail-ineligible-voters",
    ),
    path(
        "elections/<int:election_id>/audit-log",
        election_audit_log_api,
        name="api-election-audit-log",
    ),
    path(
        "elections/<int:election_id>/audit-summary",
        election_audit_summary_api,
        name="api-election-audit-summary",
    ),
    path(
        "elections/<int:election_id>/extend-end",
        election_extend_end_api,
        name="api-election-extend-end",
    ),
    path(
        "elections/<int:election_id>/conclude",
        election_conclude_api,
        name="api-election-conclude",
    ),
    path(
        "elections/<int:election_id>/tally",
        election_tally_api,
        name="api-election-tally",
    ),
    path(
        "elections/<int:election_id>/send-mail-credentials",
        election_send_mail_credentials_api,
        name="api-election-send-mail-credentials",
    ),
    path(
        "elections/<int:election_id>/public/ballots",
        election_public_ballots,
        name="api-election-public-ballots",
    ),
    path(
        "elections/<int:election_id>/public/audit",
        election_public_audit,
        name="api-election-public-audit",
    ),
    path(
        "elections/reports/turnout",
        elections_turnout_report_api,
        name="api-elections-turnout-report",
    ),
    path(
        "elections/reports/turnout/detail",
        elections_turnout_report_detail_api,
        name="api-elections-turnout-report-detail",
    ),
    path(
        "elections/<int:election_id>/vote",
        election_vote_api,
        name="api-election-vote",
    ),
    path(
        "elections/<int:election_id>/vote/submit",
        election_vote_submit,
        name="api-election-vote-submit",
    ),
    path(
        "elections/ballot/verify",
        ballot_verify_api,
        name="api-ballot-verify",
    ),
    path(
        "membership/request/detail",
        views_membership.membership_request_form_detail_api,
        name="api-membership-request-form-detail",
    ),
    path(
        "settings/detail",
        settings_detail_api,
        name="api-settings-detail",
    ),
    path(
        "settings/emails/validate/detail",
        settings_email_validate_detail_api,
        name="api-settings-email-validate-detail",
    ),
    path(
        "password-reset/detail",
        password_reset_detail_api,
        name="api-password-reset-detail",
    ),
    path(
        "password-reset/confirm/detail",
        password_reset_confirm_detail_api,
        name="api-password-reset-confirm-detail",
    ),
    path(
        "password-expired/detail",
        password_expired_detail_api,
        name="api-password-expired-detail",
    ),
    path(
        "otp/sync/detail",
        otp_sync_detail_api,
        name="api-otp-sync-detail",
    ),
    path(
        "register/detail",
        register_detail_api,
        name="api-register-detail",
    ),
    path(
        "register/confirm/detail",
        register_confirm_detail_api,
        name="api-register-confirm-detail",
    ),
    path(
        "register/activate/detail",
        register_activate_detail_api,
        name="api-register-activate-detail",
    ),
    path(
        "email-tools/templates/detail",
        email_templates_detail_api,
        name="api-email-templates-detail",
    ),
    path(
        "email-tools/templates/new/detail",
        email_template_create_detail_api,
        name="api-email-template-create-detail",
    ),
    path(
        "email-tools/templates/<int:template_id>/detail",
        email_template_edit_detail_api,
        name="api-email-template-edit-detail",
    ),
    path(
        "email-tools/images/detail",
        email_images_detail_api,
        name="api-email-images-detail",
    ),
    path(
        "email-tools/send-mail/detail",
        send_mail_detail_api,
        name="api-send-mail-detail",
    ),
    path(
        "organizations/<int:organization_id>/membership/request/detail",
        views_membership.membership_request_form_detail_api,
        name="api-organization-membership-request-form-detail",
    ),
    path(
        "membership/request/<int:pk>/rescind",
        views_membership.membership_request_rescind_api,
        name="api-membership-request-rescind",
    ),
    path(
        "membership/requests/<int:pk>/detail",
        views_membership.membership_request_detail_api,
        name="api-membership-request-detail",
    ),
    path(
        "membership/request/<int:pk>/approve",
        views_membership.membership_request_approve_api,
        name="api-membership-request-approve",
    ),
    path(
        "membership/request/<int:pk>/approve-on-hold",
        views_membership.membership_request_approve_on_hold_api,
        name="api-membership-request-approve-on-hold",
    ),
    path(
        "membership/request/<int:pk>/reject",
        views_membership.membership_request_reject_api,
        name="api-membership-request-reject",
    ),
    path(
        "membership/request/<int:pk>/rfi",
        views_membership.membership_request_rfi_api,
        name="api-membership-request-rfi",
    ),
    path(
        "membership/request/<int:pk>/ignore",
        views_membership.membership_request_ignore_api,
        name="api-membership-request-ignore",
    ),
    path(
        "membership/request/<int:pk>/reopen",
        views_membership.membership_request_reopen_api,
        name="api-membership-request-reopen",
    ),
    path(
        "membership/requests/bulk",
        views_membership.membership_requests_bulk_api,
        name="api-membership-requests-bulk",
    ),
    path(
        "membership/requests/pending",
        views_membership.membership_requests_pending_api,
        name="api-membership-requests-pending",
    ),
    path(
        "membership/requests/on-hold",
        views_membership.membership_requests_on_hold_api,
        name="api-membership-requests-on-hold",
    ),
    path(
        "membership/audit-log",
        views_membership.membership_audit_log_api,
        name="api-membership-audit-log",
    ),
    path(
        "membership/audit-log/detail",
        membership_audit_log_detail_api,
        name="api-membership-audit-log-detail",
    ),
    path(
        "membership/sponsors",
        views_membership.membership_sponsors_api,
        name="api-membership-sponsors",
    ),
    path(
        "membership/notes/<int:pk>/summary",
        views_membership.membership_request_notes_summary_api,
        name="api-membership-request-notes-summary",
    ),
    path(
        "membership/notes/<int:pk>",
        views_membership.membership_request_notes_api,
        name="api-membership-request-notes",
    ),
    path(
        "membership/notes/aggregate/summary",
        views_membership.membership_notes_aggregate_summary_api,
        name="api-membership-notes-aggregate-summary",
    ),
    path(
        "membership/notes/aggregate",
        views_membership.membership_notes_aggregate_api,
        name="api-membership-notes-aggregate",
    ),
    path(
        "membership/requests/<int:pk>/notes/add",
        views_membership.membership_request_notes_add_api,
        name="api-membership-request-notes-add",
    ),
    path(
        "membership/notes/aggregate/add",
        views_membership.membership_notes_aggregate_add_api,
        name="api-membership-notes-aggregate-add",
    ),
    # Account Invitations API endpoints
    path(
        "membership/invitations/pending",
        account_invitations_pending_api,
        name="api-account-invitations-pending",
    ),
    path(
        "membership/invitations/pending/detail",
        account_invitations_pending_detail_api,
        name="api-account-invitations-pending-detail",
    ),
    path(
        "membership/invitations/accepted",
        account_invitations_accepted_api,
        name="api-account-invitations-accepted",
    ),
    path(
        "membership/invitations/accepted/detail",
        account_invitations_accepted_detail_api,
        name="api-account-invitations-accepted-detail",
    ),
    path(
        "membership/invitations/refresh",
        account_invitations_refresh_api,
        name="api-account-invitations-refresh",
    ),
    path(
        "membership/invitations/<int:pk>/resend",
        account_invitations_resend_api,
        name="api-account-invitations-resend",
    ),
    path(
        "membership/invitations/<int:pk>/dismiss",
        account_invitations_dismiss_api,
        name="api-account-invitations-dismiss",
    ),
    path(
        "membership/invitations/bulk",
        account_invitations_bulk_api,
        name="api-account-invitations-bulk",
    ),
    # Stats API endpoints
    path(
        "stats/membership/summary/detail",
        stats_membership_summary_api,
        name="api-stats-membership-summary-detail",
    ),
    path(
        "stats/membership/charts/composition/detail",
        stats_membership_composition_charts_detail_api,
        name="api-stats-membership-composition-charts-detail",
    ),
    path(
        "stats/membership/charts/trends/detail",
        stats_membership_trends_charts_detail_api,
        name="api-stats-membership-trends-charts-detail",
    ),
    path(
        "stats/membership/charts/retention/detail",
        stats_membership_retention_chart_detail_api,
        name="api-stats-membership-retention-chart-detail",
    ),
]
