version: '3.8'

services:
  web:
    environment:
      - ASTRA_E2E_MODE=True
      - ASTRA_E2E_FAKE_FREEIPA_ENABLED=True
      - DJANGO_VITE_DEV_MODE=False
      - DJANGO_AUTO_MIGRATE=1
      - PUBLIC_BASE_URL=${PUBLIC_BASE_URL:-http://127.0.0.1:18000}
      - AWS_S3_DOMAIN=${AWS_S3_DOMAIN:-http://127.0.0.1:19000}