# Generated by Django 6.0.1 on 2026-02-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_create_org_sponsorship_expired_email_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiplog',
            name='action',
            field=models.CharField(choices=[('requested', 'Requested'), ('on_hold', 'On Hold'), ('resubmitted', 'Resubmitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('ignored', 'Ignored'), ('rescinded', 'Rescinded'), ('representative_changed', 'Representative changed'), ('expiry_changed', 'Expiry changed'), ('terminated', 'Terminated')], max_length=32),
        ),
    ]
