# Generated by Django 6.0.1 on 2026-02-10 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_remove_dead_membership_invitation_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipTypeCategory',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('is_individual', models.BooleanField(default=False, help_text='Whether types in this category can be held by individual users.')),
                ('is_organization', models.BooleanField(default=False, help_text='Whether types in this category can be held by organizations.')),
            ],
            options={
                'verbose_name': 'Membership type category',
                'verbose_name_plural': 'Membership type categories',
                'ordering': ('name',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='membership',
            name='uniq_membership_target_username_type',
        ),
        migrations.RemoveConstraint(
            model_name='membershiprequest',
            name='uniq_membershiprequest_open_org_type',
        ),
        migrations.AddField(
            model_name='membership',
            name='target_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.organization'),
        ),
        migrations.AddField(
            model_name='membership',
            name='target_organization_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='membership',
            name='target_organization_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='membership',
            name='target_username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='membership_level',
            field=models.ForeignKey(blank=True, limit_choices_to={'category__is_organization': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='core.membershiptype'),
        ),
        migrations.AddConstraint(
            model_name='membershiprequest',
            constraint=models.UniqueConstraint(condition=models.Q(('requested_organization__isnull', False), ('status__in', ['pending', 'on_hold'])), fields=('requested_organization', 'membership_type'), name='uniq_membershiprequest_open_org_type'),
        ),
        migrations.AddField(
            model_name='membership',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Denormalized from membership_type.category for UniqueConstraint.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.membershiptypecategory'),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Broad category: individual, mirror, or sponsorship.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='membership_types', to='core.membershiptypecategory'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['target_organization'], name='m_org_tgt'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('target_username', ''), _negated=True), fields=('target_username', 'membership_type'), name='uniq_membership_target_username_type'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('target_organization__isnull', False)), fields=('target_organization', 'membership_type'), name='uniq_membership_org_type'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('target_organization__isnull', False)), fields=('target_organization', 'category'), name='uniq_membership_org_category'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('target_username', ''), _negated=True), ('target_organization__isnull', True), ('target_organization_code', '')), models.Q(('target_username', ''), ('target_organization__isnull', False)), _connector='OR'), name='chk_membership_exactly_one_target'),
        ),
    ]
