# Generated by Django 6.0.1 on 2026-02-18 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_note_membership_request_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationCSVImportLink',
            fields=[
            ],
            options={
                'verbose_name': 'Organization import (CSV)',
                'verbose_name_plural': 'Organization import (CSV)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.organization',),
        ),
        migrations.CreateModel(
            name='OrganizationMembershipCSVImportLink',
            fields=[
            ],
            options={
                'verbose_name': 'Organization membership import (CSV)',
                'verbose_name_plural': 'Organization membership import (CSV)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.organization',),
        ),
        migrations.AlterModelOptions(
            name='membershipcsvimportlink',
            options={'verbose_name': 'User membership import (CSV)', 'verbose_name_plural': 'User membership import (CSV)'},
        ),
        migrations.AlterModelOptions(
            name='membershiptypecategory',
            options={'ordering': ('sort_order', 'name'), 'verbose_name': 'Membership type category', 'verbose_name_plural': 'Membership type categories'},
        ),
    ]
