# Generated by Django 6.0.1 on 2026-02-24 10:10

from __future__ import annotations

from django.db import migrations, models


def _backfill_org_claim_accepted_usernames(apps, schema_editor) -> None:
    AccountInvitation = apps.get_model("core", "AccountInvitation")

    invitations = (
        AccountInvitation.objects.filter(
            organization_id__isnull=False,
            accepted_at__isnull=False,
            accepted_username="",
        )
        .exclude(organization__representative="")
        .select_related("organization")
    )

    for invitation in invitations.iterator():
        if invitation.organization is None:
            continue

        accepted_username = str(invitation.organization.representative or "").strip().lower()
        if not accepted_username:
            continue

        AccountInvitation.objects.filter(pk=invitation.pk, accepted_username="").update(
            accepted_username=accepted_username,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0080_organizationcsvimportlink_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountinvitation",
            name="accepted_username",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.RunPython(
            code=_backfill_org_claim_accepted_usernames,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
