# Generated by Django 6.0.2 on 2026-02-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_membershiplog_import_batch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiplog',
            name='action',
            field=models.CharField(choices=[('requested', 'Requested'), ('on_hold', 'On Hold'), ('resubmitted', 'Resubmitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('ignored', 'Ignored'), ('reopened', 'Reopened'), ('rescinded', 'Rescinded'), ('representative_changed', 'Representative changed'), ('expiry_changed', 'Expiry changed'), ('terminated', 'Terminated')], max_length=32),
        ),
    ]
