# Generated by Django 6.0.2 on 2026-02-28 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_add_candidate_tiebreak_uuid_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlogentry',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='auditlogentry',
            name='election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='core.election'),
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['organization', 'timestamp'], name='audit_org_ts'),
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['organization', 'is_public'], name='audit_org_pub'),
        ),
    ]
