# Generated by Django 6.0.2 on 2026-03-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_audit_log_entry_nullable_election_add_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlogentry',
            name='rekor_canonical_message_version',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='auditlogentry',
            name='rekor_endpoint',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='auditlogentry',
            name='rekor_integrated_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='auditlogentry',
            name='rekor_log_id',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='auditlogentry',
            name='rekor_log_index',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='auditlogentry',
            name='rekor_message_digest_hex',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
