# Generated by Django 6.0.2 on 2026-03-01

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def _anonymize_non_open_election_credentials(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Anonymize credentials for elections that are not open by nulling freeipa_username.

    Credential rows (public_id, weight) are retained for chain-of-custody.
    Only the username link is removed to match the anonymize_election() lifecycle invariant.
    """
    del schema_editor
    VotingCredential = apps.get_model("core", "VotingCredential")
    VotingCredential.objects.exclude(election__status="open").filter(
        freeipa_username__isnull=False
    ).update(freeipa_username=None)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0087_auditlogentry_rekor_canonical_message_version_and_more"),
    ]

    operations = [
        migrations.RunPython(_anonymize_non_open_election_credentials, migrations.RunPython.noop),
    ]
