# Generated by Django 6.0.2 on 2026-03-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_delete_voting_credentials_for_non_open_elections'),
    ]

    operations = [
        migrations.CreateModel(
            name='MattermostWebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(max_length=500)),
                ('channel', models.CharField(blank=True, max_length=200)),
                ('username', models.CharField(blank=True, max_length=200)),
                ('icon_url', models.URLField(blank=True, max_length=500)),
                ('enabled', models.BooleanField(default=True)),
                ('events', models.JSONField(default=list)),
                ('text', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, null=True)),
                ('props', models.JSONField(blank=True, null=True)),
                ('priority', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mattermost webhook endpoint',
                'verbose_name_plural': 'Mattermost webhook endpoints',
            },
        ),
    ]
