# Generated by Django 6.0.2 on 2026-03-05 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_mattermost_webhook_endpoint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mattermostwebhookendpoint',
            options={'verbose_name': 'Mattermost Webhook', 'verbose_name_plural': 'Mattermost Webhooks'},
        ),
    ]
