# Generated by GitHub Copilot for Plan 144.

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0090_alter_mattermostwebhookendpoint_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="MirrorMembershipValidation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed_retryable", "Failed (retryable)"),
                            ("failed_terminal", "Failed (terminal)"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("answer_fingerprint", models.CharField(blank=True, default="", max_length=64)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("claim_expires_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("noted_result_fingerprint", models.CharField(blank=True, default="", max_length=64)),
                ("noted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "membership_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mirror_validation",
                        to="core.membershiprequest",
                    ),
                ),
            ],
            options={
                "ordering": ("next_run_at", "pk"),
                "indexes": [
                    models.Index(fields=["status", "next_run_at"], name="mirror_val_status_next"),
                    models.Index(fields=["status", "claim_expires_at"], name="mirror_val_status_claim"),
                ],
            },
        ),
    ]
