# Generated by GitHub Copilot for Plan 154.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0091_mirrormembershipvalidation"),
        ("post_office", "0014_alter_email_recipient_delivery_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SESEmailCorrelationAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ses_provider_message_id", models.CharField(db_index=True, max_length=255, unique=True)),
                ("ses_request_id", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "post_office_email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ses_correlation_attempts",
                        to="post_office.email",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "pk"),
                "indexes": [
                    models.Index(fields=["post_office_email", "created_at"], name="ses_corr_email_created"),
                ],
            },
        ),
    ]
