# Generated by GitHub Copilot for Plan 136.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0092_sesemailcorrelationattempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountDeletionRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(db_index=True, max_length=255)),
                (
                    "request_source",
                    models.CharField(
                        choices=[("user_settings", "User settings"), ("admin_created", "Admin created")],
                        default="user_settings",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_review", "Pending review"),
                            ("pending_privilege_check", "Pending privilege check"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="pending_review",
                        max_length=32,
                    ),
                ),
                (
                    "reason_category",
                    models.CharField(
                        choices=[
                            ("privacy", "Privacy"),
                            ("security", "Security"),
                            ("no_longer_needed", "No longer needed"),
                            ("other", "Other"),
                        ],
                        max_length=64,
                    ),
                ),
                ("reason_text", models.TextField(blank=True, default="")),
                ("manual_review_required", models.BooleanField(default=False)),
                ("blocker_codes", models.JSONField(blank=True, default=list)),
                ("fresh_auth_at", models.DateTimeField(blank=True, null=True)),
                ("admin_outcome_notes", models.TextField(blank=True, default="")),
                ("reason_cleanup_due_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("reason_text_cleared_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created_at", "-pk"),
                "indexes": [
                    models.Index(fields=["username", "created_at"], name="adr_user_created"),
                    models.Index(fields=["status", "created_at"], name="adr_status_created"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(status__in=["pending_review", "pending_privilege_check", "approved"]),
                        fields=("username",),
                        name="uniq_active_account_deletion_request_per_user",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MembershipTerminationFeedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(db_index=True, max_length=255)),
                (
                    "trigger_source",
                    models.CharField(
                        choices=[("settings_membership_tab", "Settings membership tab")],
                        default="settings_membership_tab",
                        max_length=64,
                    ),
                ),
                (
                    "reason_category",
                    models.CharField(
                        choices=[
                            ("privacy", "Privacy"),
                            ("no_longer_needed", "No longer needed"),
                            ("duplicate", "Duplicate membership"),
                            ("other", "Other"),
                        ],
                        max_length=64,
                    ),
                ),
                ("reason_text", models.TextField(blank=True, default="")),
                ("reason_cleanup_due_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("reason_text_cleared_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "membership_log",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="termination_feedback",
                        to="core.membershiplog",
                    ),
                ),
                (
                    "membership_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="core.membershiptype"),
                ),
            ],
            options={
                "ordering": ("-created_at", "-pk"),
                "indexes": [
                    models.Index(fields=["username", "created_at"], name="mtf_user_created"),
                    models.Index(fields=["membership_type", "created_at"], name="mtf_type_created"),
                ],
            },
        ),
    ]
