# Generated by Django 6.0.6 on 2026-06-11 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_update_election_vote_receipt_template_ballot_verification_copy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freeipa_username', models.CharField(db_index=True, max_length=255)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roll', to='core.election')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('election', 'freeipa_username'), name='uniq_roll_election_username')],
            },
        ),
    ]
