#!/usr/bin/env bash
# Regenerate requirements.lock from requirements.txt.
#
# The lock pins every resolved version (transitive dependencies included) so that
# image builds are reproducible: without it, each rebuild re-resolves whatever is
# newest on PyPI that day, which is how dev and production silently ended up on
# different Django minors.
#
# Resolution happens in the Dockerfile's `resolve-deps` stage rather than on the
# host, so the versions come from the same Python and system libraries the app
# image uses.
#
# Usage:
#   scripts/update-requirements-lock.sh           # rewrite requirements.lock
#   scripts/update-requirements-lock.sh --check   # fail if it is out of date
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

CONTAINER_BIN="${ASTRA_CONTAINER_BIN:-podman}"
RESOLVE_IMAGE="${ASTRA_RESOLVE_IMAGE:-astra-resolve-deps}"
LOCK_FILE="$REPO_ROOT/requirements.lock"

check_only=false
case "${1:-}" in
    --check) check_only=true ;;
    "") ;;
    *) echo "usage: $0 [--check]" >&2; exit 2 ;;
esac

generated="$(mktemp)"
trap 'rm -f "$generated"' EXIT

echo "Building the resolve-deps stage..." >&2
"$CONTAINER_BIN" build --target resolve-deps -t "$RESOLVE_IMAGE" "$REPO_ROOT" >&2

{
    echo "# Generated by scripts/update-requirements-lock.sh -- do not edit by hand."
    echo "# Add or loosen dependencies in requirements.txt, then re-run that script."
    # `pip freeze` omits pip/setuptools/wheel by default; pinning those in a
    # constraints file breaks pip's own bootstrapping.
    "$CONTAINER_BIN" run --rm --entrypoint pip "$RESOLVE_IMAGE" freeze | LC_ALL=C sort
} > "$generated"

if [[ "$check_only" == true ]]; then
    if ! diff -u "$LOCK_FILE" "$generated"; then
        echo "requirements.lock is out of date; run scripts/update-requirements-lock.sh" >&2
        exit 1
    fi
    echo "requirements.lock is up to date." >&2
    exit 0
fi

install -m 644 "$generated" "$LOCK_FILE"
echo "Wrote $LOCK_FILE" >&2
